[project]
name = "hello-agentic-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.5.5",
    "dotenv>=0.9.9",
    "openai>=1.80.0",
    "openai-agents>=0.0.15",
    "python-dotenv>=1.1.0",
]
